config/routes.rb
 Rails.application.routes.draw do
  devise_for :users

  resources :products do
    resources :images
  end

  resources :categories
  resources :users

  resources :order_items

  resource :carts, only: [:show]

  get 'admin/', to: 'admin#dashboard'
  namespace :admin do
    resources :categories
    resources :products do
      resources :images
    end
  end

  root 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  layout 'admin'

  def index
    @categories = Category.all
  end

  def create
    @category = Category.create(category_params)
    redirect_to admin_categories_path
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path
    else
      flash[:error] = "Failed to edit category!"
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products.all.page(params[:page]).per params[:limit]
    @order_item = current_user.cart.order_items.new if current_user
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/admin/categories/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="nav-dashboard col-md-2">
      <ul class="nav nav-pills nav-stacked">
        <li class="list-nav">NAVIGATION</li>
        <li class="active"><%= link_to "Categories", admin_categories_path %></li>
        <li><%= link_to "Products", admin_products_path %></li>
      </ul>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
      <div class="content">
        <div class="ad-head-title">
          <h1>Edit Category</h1>
        </div>

        <div id="breadcrumb" class="bread-admin">
          <ul class="breadcrumb">
            <li><%= link_to "Dashboard", admin_path %></li>
            <li><%= link_to "Categories", admin_categories_path %></li>
            <li><%= link_to "Category #{@category.id}", admin_category_path(@category) %></li>
            <li>Edit</li>
          </ul>
        </div>

        <ul class="nav nav-tabs">
          <li><%= link_to '<i class="fa fa-eye"></i> Show'.html_safe, admin_category_path(@category) %></li>
          <li class="active"><%= link_to '<i class="fa fa-edit"></i> Edit'.html_safe, edit_admin_category_path(@category) %></li>
          <li><%= link_to '<i class="fa fa-trash"></i> Delete'.html_safe, [:admin, @category], method: :delete, data: { confirm: 'Are you sure?'} %></li>
        </ul>

        <%= form_for [:admin, @category] do |f| %>
          <div class="col-md-5">
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>NAME:</b></label>
              <%= f.text_field :name, placeholder: "name", required: true, class: "form-control" %>
            </div>
            <div class="form-actions">
              <%= f.submit "Save Categogy", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="nav-dashboard col-md-2">
      <ul class="nav nav-pills nav-stacked">
        <li class="list-nav">NAVIGATION</li>
        <li class="active"><%= link_to "Categories", admin_categories_path %></li>
        <li><%= link_to "Products", admin_products_path %></li>
      </ul>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
      <div class="content">
        <div class="ad-head-title">
          <h1>List of Categories</h1>
        </div>

        <div id="breadcrumb" class="bread-admin">
          <ul class="breadcrumb">
            <li><%= link_to "Dashboard", admin_path %></li>
            <li><%= link_to "Categories", admin_categories_path %></li>
          </ul>
        </div>

        <ul class="nav nav-tabs">
          <li class="active"><%= link_to '<i class="fa fa-list"></i> List'.html_safe, admin_categories_path %></li>
          <li><%= link_to '<i class="fa fa-plus"></i> Add new'.html_safe, new_admin_category_path %></li>
        </ul>

        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>NAME</th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.id %></td>
                <td><%= category.name %></td>
                <td>
                  <ul class="inline list-inline">
                    <li><%= link_to fa_icon("eye"), admin_category_path(category) %></li>
                    <li><%= link_to fa_icon("edit"), edit_admin_category_path(category) %></li>
                    <li><%= link_to fa_icon("trash"), [:admin, category], method: :delete, data: { confirm: 'Are you sure?'} %></li>
                  </ul>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="nav-dashboard col-md-2">
      <ul class="nav nav-pills nav-stacked">
        <li class="list-nav">NAVIGATION</li>
        <li class="active"><%= link_to "Categories", admin_categories_path %></li>
        <li><%= link_to "Products", admin_products_path %></li>
      </ul>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
      <div class="content">
        <div class="ad-head-title">
          <h1>New Category</h1>
        </div>

        <div id="breadcrumb" class="bread-admin">
          <ul class="breadcrumb">
            <li><%= link_to "Dashboard", admin_path %></li>
            <li><%= link_to "Categories", admin_categories_path %></li>
            <li>New</li>
          </ul>
        </div>

        <ul class="nav nav-tabs">
          <li><%= link_to '<i class="fa fa-list"></i> List'.html_safe, admin_categories_path %></li>
          <li  class="active"><%= link_to '<i class="fa fa-plus"></i> Add new'.html_safe, new_admin_category_path %></li>
        </ul>

        <%= form_for [:admin, @category] do |f| %>
          <div class="col-md-5">
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>NAME:</b></label>
              <%= f.text_field :name, placeholder: "name", required: true, class: "form-control" %>
            </div>
            <div class="form-actions">
              <%= f.submit "Save Categogy", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="nav-dashboard col-md-2">
      <ul class="nav nav-pills nav-stacked">
        <li class="list-nav">NAVIGATION</li>
        <li class="active"><%= link_to "Categories", admin_categories_path %></li>
        <li><%= link_to "Products", admin_products_path %></li>
      </ul>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
      <div class="content">
        <div class="ad-head-title">
          <h1>Show Category</h1>
        </div>

        <div id="breadcrumb" class="bread-admin">
          <ul class="breadcrumb">
            <li><%= link_to "Dashboard", admin_path %></li>
            <li><%= link_to "Categories", admin_categories_path %></li>
            <li>Category #<%= @category.id %></li>
          </ul>
        </div>

        <ul class="nav nav-tabs">
          <li class="active"><%= link_to '<i class="fa fa-eye"></i> Show'.html_safe, admin_category_path(@category) %></li>
          <li><%= link_to '<i class="fa fa-edit"></i> Edit'.html_safe, edit_admin_category_path(@category) %></li>
          <li><%= link_to '<i class="fa fa-trash"></i> Delete'.html_safe, [:admin, @category], method: :delete, data: { confirm: 'Are you sure?'} %></li>
        </ul>

        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>NAME</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @category.id %></td>
              <td><%= @category.name %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>