config/routes.rb
 Rails.application.routes.draw do
  devise_for :users

  resources :products do
    resources :images
  end

  resources :categories
  resources :users

  resources :order_items

  resource :carts, only: [:show]

  get 'admin/', to: 'admin#dashboard'
  namespace :admin do
    resources :categories
    resources :products do
      resources :images
    end
  end

  root 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images, dependent: :destroy
  belongs_to :category, optional: true
  has_many :order_items
  validates :code, presence: true, uniqueness: true
  accepts_nested_attributes_for :images, allow_destroy: true,
                                reject_if: proc { |att| att['image_url'].blank? }

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  layout 'admin'

  def index
    @products = Product.all.page(params[:page]).per(10)
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        UpdateProductJob.perform_later(@product)
        format.html { redirect_to admin_products_path }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @categories = Category.all
    @product = Product.new
    @image = @product.images.build
  end

  def edit
    @product = Product.find(params[:id])
    @images = @product.images.all
  end

  def show
    @product = Product.find(params[:id])
    @images = @product.images.all
  end

  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to admin_product_path(@product) }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product)
          .permit(:name, :price, :code, :description, :category_id,
                  images_attributes: Image.attribute_names.map(&:to_sym).push(:_destroy))
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = @q.result(distinct:true).page(params[:page]).per params[:limit]
  end

  def show
    @product = Product.find(params[:id])
    @order_item = current_user.cart.order_items.new if current_user
  end

  private
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/views/admin/products/_image_fields.html.erb
<div class="nested-fields row">
  <div class="col-sm-7 input-file">
    <%= f.file_field :image_url %>
    <%= f.hidden_field :image_url_cache, value: f.object.image_url_cache %>
  </div>
  <div class="thumb col-sm-3">
    <% if f.object.image_url.url.present? %>
      <%= image_tag f.object.image_url.url %>
    <% end %>
  </div>
  <div class="col-sm-2 remove">
     <%= link_to_remove_association '<i class="fa fa-times"></i>'.html_safe, f, class: "remove-pic" %>
  </div>

</div>

app/views/admin/products/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="nav-dashboard col-md-2">
      <ul class="nav nav-pills nav-stacked">
        <li class="list-nav">NAVIGATION</li>
        <li><%= link_to "Categories", admin_categories_path %></li>
        <li class="active"><%= link_to "Products", admin_products_path %></li>
      </ul>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
      <div class="content">
        <div class="ad-head-title">
          <h1>Edit Product</h1>
        </div>

        <div id="breadcrumb" class="bread-admin">
          <ul class="breadcrumb">
            <li><%= link_to "Dashboard", admin_path %></li>
            <li><%= link_to "Products", admin_products_path %></li>
            <li><%= link_to "Product #{@product.id}", admin_product_path(@product) %></li>
            <li>Edit</li>
          </ul>
        </div>

        <ul class="nav nav-tabs">
          <li><%= link_to '<i class="fa fa-eye"></i> Show'.html_safe, admin_product_path(@product) %></li>
          <li class="active"><%= link_to '<i class="fa fa-edit"></i> Edit'.html_safe, edit_admin_product_path(@product) %></li>
          <li><%= link_to '<i class="fa fa-trash"></i> Delete'.html_safe, [:admin, @product], method: :delete, data: { confirm: 'Are you sure?'} %></li>
        </ul>

        <%= form_for([:admin, @product], html: {multipart: true}) do |f| %>
          <div class="col-md-5" style="margin-bottom:20px">
            <% if @product.errors.any? %>
              <div class="alert alert-error">
                <ul>
                <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>Category:</b></label>
              <%= f.select :category_id, options_from_collection_for_select(Category.all, "id", "name"), {}, {:class => "form-control"} %>
            </div>
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>Code</b></label>
              <%= f.text_field :code, required: true, class: "form-control" %>
            </div>
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>Name</b></label>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>Price</b></label>
              <%= f.text_field :price, class: "form-control" %>
            </div>
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>Description</b></label>
              <%= f.text_area :description, class: "form-control" %>
            </div>
            <div class="form-group add-img">
              <%= link_to_add_association 'Add Image', f, :images, class: "btn btn-warning" %>
              <div class="image-form">
                <%= f.fields_for :images do |img| %>
                  <%= render "image_fields", f: img %>
                <% end %>
              </div>
            </div>
            <div class="form-actions">
              <%= f.submit "Save Product", class: "btn btn-primary" %>
              <%= link_to "Back Product's Page", admin_products_path(), class: "btn btn-info" %>
            </div>
          </div>
          <br><br>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container-fluid">
    <div class="row">
      <div class="nav-dashboard col-md-2">
        <ul class="nav nav-pills nav-stacked">
          <li class="list-nav">NAVIGATION</li>
          <li><%= link_to "Categories", admin_categories_path %></li>
          <li class="active"><%= link_to "Products", admin_products_path %></li>
        </ul>
      </div>

      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
        <div class="content">
          <div class="ad-head-title">
            <h1>List of produtcs</h1>
          </div>

          <div id="breadcrumb" class="bread-admin">
            <ul class="breadcrumb">
              <li><%= link_to "Dashboard", admin_path %></li>
              <li><%= link_to "Products", admin_products_path %></li>
            </ul>
          </div>

          <ul class="nav nav-tabs">
            <li class="active"><%= link_to '<i class="fa fa-list"></i> List'.html_safe, admin_products_path %></li>
            <li><%= link_to '<i class="fa fa-plus"></i> Add new'.html_safe, new_admin_product_path %></li>
          </ul>

          <table class="table">
            <thead>
              <tr>
                <th>CODE</th>
                <th>NAME</th>
                <th>PRICE</th>
                <th>CATEGORY</th>
                <th>DESCRIPTION</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @products.each do |product| %>
                <tr>
                  <td><%= product.code %></td>
                  <td><%= product.name %></td>
                  <td><%= product.price %></td>
                  <td><%= product.category.name unless product.category.nil? %></td>
                  <td><%= product.description.truncate(30) unless product.description.nil? %></td>
                  <td>
                    <ul class="inline list-inline">
                    <li><%= link_to fa_icon("eye"), admin_product_path(product) %></li>
                    <li><%= link_to fa_icon("edit"), edit_admin_product_path(product) %></li>
                    <li><%= link_to fa_icon("trash"), [:admin, product], method: :delete, data: { confirm: 'Are you sure?'} %></li>
                    </ul>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @products, theme: 'twitter-bootstrap-3' %>
        </div>
      </div>
    </div>
</div>

app/views/admin/products/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="nav-dashboard col-md-2">
      <ul class="nav nav-pills nav-stacked">
        <li class="list-nav">NAVIGATION</li>
        <li><%= link_to "Categories", admin_categories_path %></li>
        <li class="active"><%= link_to "Products", admin_products_path %></li>
      </ul>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
      <div class="content">
        <div class="ad-head-title">
          <h1>New Product</h1>
        </div>

        <div id="breadcrumb" class="bread-admin">
          <ul class="breadcrumb">
            <li><%= link_to "Dashboard", admin_path %></li>
            <li><%= link_to "Products", admin_products_path %></li>
            <li>New</li>
          </ul>
        </div>

        <ul class="nav nav-tabs">
          <li><%= link_to '<i class="fa fa-list"></i> List'.html_safe, admin_products_path %></li>
          <li  class="active"><%= link_to '<i class="fa fa-plus"></i> Add new'.html_safe, new_admin_product_path %></li>
        </ul>

        <%= form_for([:admin, @product], html: {multipart: true}) do |f| %>
          <div class="col-md-5">
            <% if @product.errors.any? %>
              <div class="alert alert-error">
                <ul>
                <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>Category:</b></label>
              <%= f.select :category_id, options_from_collection_for_select(Category.all, "id", "name"), {include_blank: "Select Category"}, {:class => "form-control"} %>
            </div>
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>Code</b></label>
              <%= f.text_field :code, required: true, class: "form-control" %>
            </div>
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>Name</b></label>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>Price</b></label>
              <%= f.text_field :price, class: "form-control" %>
            </div>
            <div class="form-group">
              <label class="col-sm-2 col-form-label"><b>Description</b></label>
              <%= f.text_area :description, class: "form-control" %>
            </div>
            <div class="form-group add-img">
              <%= link_to_add_association 'Add Image', f, :images, class: "btn btn-warning" %>
              <div class="image-form">
                <%= f.fields_for :images do |img| %>
                  <%= render "image_fields", f: img %>
                <% end %>
              </div>
            </div>
            <div class="form-actions">
              <%= f.submit "Save Product", class: "btn btn-primary" %>
              <%= link_to "Back Product's Page", admin_products_path(), class: "btn btn-info" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="nav-dashboard col-md-2">
      <ul class="nav nav-pills nav-stacked">
        <li class="list-nav">NAVIGATION</li>
        <li><%= link_to "Categories", admin_categories_path %></li>
        <li class="active"><%= link_to "Products", admin_products_path %></li>
      </ul>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
      <div class="content">
        <div class="ad-head-title">
          <h1>Show Product</h1>
        </div>

        <div id="breadcrumb" class="bread-admin">
          <ul class="breadcrumb">
            <li><%= link_to "Dashboard", admin_path %></li>
            <li><%= link_to "Products", admin_products_path %></li>
            <li>Product #<%= @product.id %></li>
          </ul>
        </div>

        <ul class="nav nav-tabs">
          <li class="active"><%= link_to '<i class="fa fa-eye"></i> Show'.html_safe, admin_product_path(@product) %></li>
          <li><%= link_to '<i class="fa fa-edit"></i> Edit'.html_safe, edit_admin_product_path(@product) %></li>
          <li><%= link_to '<i class="fa fa-trash"></i> Delete'.html_safe, [:admin, @product], method: :delete, data: { confirm: 'Are you sure?'} %></li>
        </ul>

        <table class="table">
          <thead>
            <tr>
              <th>CODE</th>
              <th>NAME</th>
              <th>PRICE</th>
              <th>CATEGORY</th>
              <th>DESCRIPTION</th>
              <th>IMAGES</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @product.code %></td>
              <td><%= @product.name %></td>
              <td><%= @product.price %></td>
              <td><%= @product.category.name %></td>
              <td><%= @product.description.truncate(20) %></td>
              <td>
                <% @images.each do |img| %>
                  <%= image_tag img.image_url, style: "max-width: 40px; max-height: 40px" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>