config/routes.rb
 Rails.application.routes.draw do
  devise_for :users

  resources :products do
    resources :images
  end

  resources :categories
  resources :users

  resources :order_items

  resource :carts, only: [:show]

  get 'admin/', to: 'admin#dashboard'
  namespace :admin do
    resources :categories
    resources :products do
      resources :images
    end
  end

  root 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images, dependent: :destroy
  belongs_to :category, optional: true
  has_many :order_items
  validates :code, presence: true, uniqueness: true
  accepts_nested_attributes_for :images, allow_destroy: true,
                                reject_if: proc { |att| att['image_url'].blank? }

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  layout 'admin'

  def index
    @products = Product.all.page(params[:page]).per(10)
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        UpdateProductJob.perform_later(@product)
        format.html { redirect_to admin_products_path }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @categories = Category.all
    @product = Product.new
    @image = @product.images.build
  end

  def edit
    @product = Product.find(params[:id])
    @images = @product.images.all
  end

  def show
    @product = Product.find(params[:id])
    @images = @product.images.all
  end

  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to admin_product_path(@product) }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product)
          .permit(:name, :price, :code, :description, :category_id,
                  images_attributes: Image.attribute_names.map(&:to_sym).push(:_destroy))
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = @q.result(distinct:true).page(params[:page]).per params[:limit]
  end

  def show
    @product = Product.find(params[:id])
    @order_item = current_user.cart.order_items.new if current_user
  end

  private
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/views/products/index.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div id="main" class="col-md-12">
        <div class="store-filter clearfix">
          <div class="pull-left">
            <h3 id="result-search">Ket qua tim kiem cho <%= @q.name_cont %></h3>
          </div>
          <div class="pull-right">
            <span class="text-uppercase">Show:</span>
            <div class="page-filter">
              <%= search_form_for @q, url: products_path do |f|%>
                <%= select_tag :limit, options_from_collection_for_select(Settings.show_limit, :second, :second, selected: params[:limit] || Settings.show_limit.limit),id: "show-limit",class: "input" %>
                <%= f.submit "search", class: "btn btn-info", style: "display: none; margin-right: 10px"%>
              <% end %>
            </div>
            <ul class="store-pages">
               <li><span class="text-uppercase">Page:</span></li>
               <%= paginate @products %>
            </ul>
          </div>
        </div>

        <div id="store">
          <div class="row">
            <% @products.each do |product| %>
            <div class="col-md-3 col-sm-6 col-xs-6">
              <div class="product product-single">
                <div class="product-thumb">
                  <div class="product-label">
                    <span>New</span>
                    <span class="sale">-20%</span>
                  </div>
                  <%= image_tag product.images.first.image_url.url %>
                </div>
                <div class="product-body">
                  <h3 class="product-price"><%= product.price %></h3>
                  <div class="product-rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o empty"></i>
                  </div>
                  <h2 class="product-name"><a href="#"><%= link_to product.name.truncate(20), product_path(product.id) %></a></h2>
                  <% if current_user %>
                    <div class="product-btns">
                      <button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
                      <button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
                      <%= button_to 'Add to Cart', order_items_path(:product_id => product), :remote => true, class: "primary-btn add-to-cart" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<!-- BREADCRUMB -->
<div id="breadcrumb">
  <div class="container">
    <ul class="breadcrumb">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to @product.category.name, category_path(@product.category_id) %></li>
      <li><%= link_to "Products", products_path %></li>
      <li class="active"><%= @product.name %></li>
    </ul>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="row">
      <div class="product product-details clearfix">
        <div class="col-md-6">
          <div id="product-main-view">
            <% @product.images.each do |img| %>
              <div class="product-view">
                <%= image_tag img.image_url.url %>
              </div>
            <% end %>
          </div>
          <div id="product-view">
            <% @product.images.each do |img| %>
              <div class="product-view">
                <%= image_tag img.image_url.url %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="product-body">
            <div class="product-label">
              <span>New</span>
              <span class="sale">-20%</span>
            </div>
            <h2 class="product-name"><%= @product.name %></h2>
            <h3 class="product-price"><%= @product.price %></h3>
            <div>
              <div class="product-rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o empty"></i>
              </div>
              <a href="#">3 Review(s) / Add Review</a>
            </div>
            <p><%= @product.description %></p>
            <% if current_user %>
              <div class="product-btns">
                <%= button_to 'Add to Cart', order_items_path(:product_id => @product), :remote => true, class: "primary-btn add-to-cart" %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-md-12">
          <div class="product-tab">
            <ul class="tab-nav">
              <li class="active"><a data-toggle="tab" href="#tab1">Description</a></li>
              <li><a data-toggle="tab" href="#tab1">Details</a></li>
              <li><a data-toggle="tab" href="#tab2">Reviews (3)</a></li>
            </ul>
            <div class="tab-content">
              <div id="tab1" class="tab-pane fade in active">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              </div>
              <div id="tab2" class="tab-pane fade in">
                <div class="row">
                  <div class="col-md-6">
                    <div class="product-reviews">
                      <div class="single-review">
                        <div class="review-heading">
                          <div><a href="#"><i class="fa fa-user-o"></i> John</a></div>
                          <div><a href="#"><i class="fa fa-clock-o"></i> 27 DEC 2017 / 8:0 PM</a></div>
                          <div class="review-rating pull-right">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o empty"></i>
                          </div>
                        </div>
                        <div class="review-body">
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute
                          irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                        </div>
                      </div>

                      <div class="single-review">
                        <div class="review-heading">
                          <div><a href="#"><i class="fa fa-user-o"></i> John</a></div>
                          <div><a href="#"><i class="fa fa-clock-o"></i> 27 DEC 2017 / 8:0 PM</a></div>
                          <div class="review-rating pull-right">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o empty"></i>
                          </div>
                        </div>
                        <div class="review-body">
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute
                          irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                        </div>
                      </div>

                      <div class="single-review">
                        <div class="review-heading">
                          <div><a href="#"><i class="fa fa-user-o"></i> John</a></div>
                          <div><a href="#"><i class="fa fa-clock-o"></i> 27 DEC 2017 / 8:0 PM</a></div>
                          <div class="review-rating pull-right">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o empty"></i>
                          </div>
                        </div>
                        <div class="review-body">
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute
                          irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                        </div>
                      </div>
                      <ul class="reviews-pages">
                        <li class="active">1</li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#"><i class="fa fa-caret-right"></i></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <h4 class="text-uppercase">Write Your Review</h4>
                    <p>Your email address will not be published.</p>
                    <form class="review-form">
                      <div class="form-group">
                        <input class="input" type="text" placeholder="Your Name" />
                      </div>
                      <div class="form-group">
                        <input class="input" type="email" placeholder="Email Address" />
                      </div>
                      <div class="form-group">
                        <textarea class="input" placeholder="Your review"></textarea>
                      </div>
                      <div class="form-group">
                        <div class="input-rating">
                          <strong class="text-uppercase">Your Rating: </strong>
                          <div class="stars">
                            <input type="radio" id="star5" name="rating" value="5" /><label for="star5"></label>
                            <input type="radio" id="star4" name="rating" value="4" /><label for="star4"></label>
                            <input type="radio" id="star3" name="rating" value="3" /><label for="star3"></label>
                            <input type="radio" id="star2" name="rating" value="2" /><label for="star2"></label>
                            <input type="radio" id="star1" name="rating" value="1" /><label for="star1"></label>
                          </div>
                        </div>
                      </div>
                      <button class="primary-btn">Submit</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>